name: Deploy to Elastic Beanstalk - Frontend

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    env:
      AWS_REGION: us-east-1
      EB_BACKEND_ENV: aroma-delivery-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '18'

#      - name: Install dependencies
#        run: npm install

#      - name: Build frontend
#        run: npm run build

      - name: Generate deploy package
        run: zip -r aromadelivery-ui.zip * -x "**.git**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: aroma-delivery-ui
          environment_name: aroma-delivery-ui-env
          version_label: "app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: aromadelivery-ui.zip
      - name: Deployed!
        run: echo App deployed to ELB